name: My First Workflow

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.save-artifact.outputs.path }}
    steps:
      - name: Install cowsay program
        run: sudo apt-get update && sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" > dragon.txt

      - name: Save dragon.txt as artifact
        id: save-artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon-artifact
          path: dragon.txt

      - name: Sleep for 30 seconds
        run: sleep 30

  test_job_2:
    runs-on: ubuntu-latest
    needs: build_job_1
    steps:
      - name: Download dragon.txt artifact
        uses: actions/download-artifact@v4
        with:
          name: dragon-artifact

      - name: Sleep for 10 seconds
        run: sleep 10

      - name: Test file exists and contains 'dragon'
        run: grep -i "dragon" dragon.txt

  deploy_job_3:
    runs-on: ubuntu-latest
    needs: test_job_2
    steps:
      - name: Download dragon.txt artifact
        uses: actions/download-artifact@v4
        with:
          name: dragon-artifact

      - name: Read file contents
        run: cat dragon.txt