name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List and Read file
        run: |
          echo "My first Github Actions job"
          ls -ltra
          cat README.md
      - name: Executing Shell scipt
        run: 
             chmod +x ./.github/workflows/ascii-script.sh
            ./.github/workflows/ascii-script.sh

    #   - name: Install cowsay
    #     run: sudo apt-get update && sudo apt-get install -y cowsay

    #   - name: Generate ASCII Artwork
    #     run: cowsay -f dragon "Run for cover, I am a Dragon ... RAWR" >> dragon.txt
       
    #   - name: Read file
    #     run: cat dragon.txt